### ISSUE TITLE
foliavalidator uses "non-standard" quotes in xml header output

### ISSUE THREAD

**Issue by kosloot** [proycon/foliapy#20]
Minor detail, but foliavalidator uses `'` and not `"` in its xml header output, even when the input uses `"`.
This makes comparing results a bit more difficult.

Example:
Input:
```
<?xml version="1.0" encoding="utf-8"?>
```
Output:
```
<?xml version='1.0' encoding='utf-8'?>
```

This is not invalid, but just an annoyance.
Also, the "standard" would be to output "UTF-8" instead of "utf-8", that would also be 'nice to have'.
otoh: that would make comparing more difficult again. maybe libfolia should add an exception for files where utf-8 is mentioned....

**Comment by proycon** [comment]
If I recall correctly this was in lxml (or libxml2 even?) so not something I have control over. Closing the issue.
